plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0'
    id 'io.spring.dependency-management' version '1.1.5'
    id 'jacoco'
    id 'checkstyle'
    id 'com.github.spotbugs' version '6.0.26'
}

group = 'com.demo'
version = '1.0.0'

java {
    sourceCompatibility = '21'
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.liquibase:liquibase-core'
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:postgresql'
    // Add this to ensure compatibility with Java 21 (ASM is required for bytecode analysis)
//    spotbugs 'com.github.spotbugs:spotbugs:4.8.6'
//    spotbugsPlugins 'com.h3xstream.findsecbugs:findsecbugs-plugin:1.12.0'
//    spotbugsPlugins 'org.ow2.asm:asm:9.6' // Ensure compatibility with Java 21 bytecode
}

tasks.named('test') {
    useJUnitPlatform()
}

configurations.all {
    exclude group: 'org.junit', module: 'junit'
}

jacoco {
    toolVersion = "0.8.12"
}

tasks.test {
    // Ensure the report is generated after tests
    finalizedBy tasks.jacocoTestReport
}

tasks.jacocoTestReport {
    // Ensure tests are run before generating the report
    dependsOn tasks.test

    reports {
        xml.required.set(true)
        csv.required.set(false)
        // Generate HTML report
        html.required.set(true)
    }
}

tasks.jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                // Ensure at least 80% overall branch coverage
                counter = 'BRANCH'
                value = 'COVEREDRATIO'
                minimum = 0.80
            }
        }
        rule {
            limit {
                // Ensure at least 80% overall line coverage
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.25
            }
        }
    }
}

check {
    dependsOn 'checkstyleMain', 'checkstyleTest', 'spotbugsMain', 'spotbugsTest', 'jacocoTestCoverageVerification'
}

checkstyle {
    toolVersion = '10.12.0'
    // Path to Checkstyle config file
    configFile = rootProject.file('config/checkstyle/checkstyle.xml')
}

tasks.checkstyleMain {
    reports {
        xml.required.set(false) // Disable XML report
        html.required.set(true) // Enable HTML report
    }
}

tasks.checkstyleTest {
    reports {
        xml.required.set(false)
        html.required.set(true)
    }
}

spotbugs {
    toolVersion = '4.8.6'
}

tasks.spotbugsMain {
    ignoreFailures = false
    reports {
        xml.required.set(false) // Disable XML report
        html.required.set(true) // Enable HTML report
    }
}

tasks.spotbugsTest {
    ignoreFailures = false
    reports {
        xml.required.set(false)
        html.required.set(true)
    }
}