spring:
  threads:
    virtual:
      enabled: true
  task:
    execution:
      simple:
        concurrency-limit: 10
    scheduling:
      simple:
        concurrency-limit: 10
  main:
    banner-mode: "off"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test-db
    username: test
    password: test@123
  jpa:
    show-sql: false
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-main.yaml
logging:
  level:
    org.springframework.data.jpa: DEBUG
